#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

robots_txt_default() {
  declare desc="display robots.txt configration"
  local cmd="$1"
  [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
  local APP="$2"; verify_app_name "$APP"
  dokku_log_info2 "$APP robots.txt"
  cat "$DOKKU_ROOT/$APP/robots.txt"
}

robots_txt_default "$@"
